function map(mode, rhs, lhs)
    vim.api.nvim_set_keymap(mode, rhs, lhs, { noremap = true })
end

map("i", "(", "(<ESC>i)")
map("i", "{}", "{}<ESC>i")
map("i", "{<CR>", "{<CR}<ESC>O")
map("i", "[]", "[]<ESC>i")
map("i", "\"", "\"\"<ESC>i")
map("i", "'", "''<ESC>i")
map("n", "-", "ddp")
map("n", "-", "ddkP")
map("i", "<c-u>", "<ESC>lvwUa")
map("n", "<c-U>", "vA<ESC>U<ESC>")
map("n", "<leader>ev", ":vs $MYVIMRC<CR>")
